# The name of your Flutter app (change as needed)
name: pimflutter

# A short description of the project
description: "A new Flutter project."

# Prevents this app from being accidentally published to pub.dev
publish_to: 'none'

# The version number of the app: major.minor.patch+build
version: 1.0.0+1

# The environment defines which Dart SDK version your app supports
environment:
  sdk: '>=3.7.0 <4.0.0'

# List of packages your app depends on to function properly
dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons package
  cupertino_icons: ^1.0.8

  # Access the camera in real time
  camera: ^0.11.1
  # access to local storage 
  shared_preferences: ^2.2.2

  # TensorFlow Lite support for object detection
  tflite_flutter: ^0.11.0
  # Image manipulation package (used with TFLite in preprocessing)
  image: ^3.2.2

  # HTTP client for networking (used with REST APIs)
  dio: ^5.0.0

  # Classic HTTP support (alternative or in combination with Dio)
  http: ^1.3.0

  # Secure key/value storage for tokens and preferences
  flutter_secure_storage: ^9.2.4

  # Picking images from camera/gallery
  image_picker: ^0.8.4+7

  # To request runtime permissions (camera, storage, etc.)
  permission_handler: ^11.4.0

  # Check internet connection status (Wi-Fi, mobile, offline)
  connectivity_plus: ^5.0.2

# Dependencies used only during development and testing
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linter package to enforce good code practices
  flutter_lints: ^5.0.0

# Flutter-specific configuration
flutter:
  # Enables the use of Material Design icons
  uses-material-design: true

  # Asset files to include in your app (images, model files, etc.)
  assets:
    - assets/yolov5.tflite
    - assets/labels.txt
    - assets/logo.png               # Labels for object detection classes
    - assets/background.jpg
    - assets/facebook.png
    - assets/google.png
    - assets/energy.png
    - assets/food.png
    - assets/transport.png
    - assets/phone.png
    - assets/number1.png
    - assets/number2.png
    - assets/number3.png
    - assets/Tshirt.png
    - assets/Shirt.png
    - assets/Pullover.png
    - assets/Dress.png
    - assets/Skirt.png
    - assets/Jacket.png
    - assets/Jeans.png
    - assets/Sweater.png
    - assets/Shorts.png
    - assets/Hanger_icon.png
    - assets/eco_friendly_scan.png
    - assets/object_detection.png     # Custom icon for object detection card
    - assets/detection_logo.png    # Custom icon for object detection card